easy_admin:
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
            js:
    site_name: 'Wello Horld'
    entities:
        # List the entity class name you want to manage
        Material:
            class: App\Entity\Material
            list:
#                fields:
#                    - { property: 'available', type: 'toggle'}
# , trans: true, domain: 'materials'
        Model:
            class: App\Entity\Model
            form:
                fields:
                    - { property: 'modelFile', type: 'vich_file' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - title
                    - public
                    - creator
                    - { property: 'price', help: 'A json with quantity factor for each part'}
            list:
                fields:
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
                    - title
                    - public
                    - creator
                    - { property: 'price', help: 'A json with quantity factor for each part'}
            show:
                fields:
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
        User:
            class: App\Entity\User
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            form:
                fields:
                    - id
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'role', type: 'choice', type_options: {choices:{ User: 'ROLE_USER', Admin: 'ROLE_ADMIN'}}}
            new:
                fields:
                    - '-id'
            edit:
                fields:
                    - { property: 'passwordResetToken', type: 'text', type_options: { disabled: true }}
            list:
                fields:
                    - id
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'passwordResetToken', type: 'boolean'}
                    - { property: 'role', type: 'string'}
#        - App\Entity\Print
