easy_admin:
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
            js:
        menu:
            - { label: 'Go to site', url: '/' }
            - { label: 'Models', entity: 'Model' }
            - { label: 'Product attributes', entity: 'ProductAttribute' }
            - { label: 'Attributes categories', entity: 'VariableAttributeCategory' }
            - { label: 'Attributes', entity: 'VariableAttribute' }
            - { label: 'Users', entity: 'User' }
    site_name: '%app.name% admin'
    entities:
        Model:
            class: App\Entity\Model
            form:
                fields:
                    - { property: 'modelFile', type: 'vich_file' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - title
                    - slug
                    - public
                    - user
                    - basePrice
                    - { property: 'attributes', type_options: { by_reference: false} }
            new:
                fields:
                    - { property: 'modelFile', type: 'vich_file', type_options: { required: false } }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
                    - { property: 'slug', type_options: { required: false, attr: { placeholder: 'Leave empty for auto'} } }
            list:
                fields:
                    - id
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
                    - title
                    - slug
                    - public
                    - user
                    - basePrice
                    - attributes
            show:
                fields:
                    - id
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
                    - title
                    - slug
                    - public
                    - user
                    - basePrice
                    - attributes
        # List the entity class name you want to manage
        ProductAttribute:
            class: App\Entity\ProductAttribute
        VariableAttributeCategory:
            class: App\Entity\VariableAttributeCategory
            form:
                fields:
                    - name
                    - { property: 'productAttributes', type_options: { by_reference: false} }
                    - { property: 'attributes', type_options: { by_reference: false} }
        VariableAttribute:
            class: App\Entity\VariableAttribute
        User:
            class: App\Entity\User
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            form:
                fields:
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'role', type: 'choice', type_options: {choices:{ User: 'ROLE_USER', Admin: 'ROLE_ADMIN'}}}
            edit:
                fields:
                    - { property: 'passwordResetToken', type: 'text', type_options: { disabled: true }}
            list:
                fields:
                    - id
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'passwordResetToken', type: 'boolean'}
                    - { property: 'role', type: 'string'}
#        - App\Entity\Print
