easy_admin:
    design:
        brand_color: '#1ABC9C'
        assets:
            css:
            js:
    site_name: 'Wello Horld'
    entities:
        Model:
            class: App\Entity\Model
            form:
                fields:
                    - { property: 'modelFile', type: 'vich_file' }
                    - { property: 'imageFile', type: 'vich_image' }
                    - title
                    - slug
                    - public
                    - creator
                    - { property: 'masses', type: 'text', help: 'A json with format <code>"partname": mass_in_kg</code>'}
            new:
                fields:
                    - { property: 'modelFile', type: 'vich_file', type_options: { required: false } }
                    - { property: 'imageFile', type: 'vich_image', type_options: { required: false } }
                    - { property: 'slug', type_options: { required: false } }
            list:
                fields:
                    - id
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
                    - title
                    - slug
                    - public
                    - creator
                    - { property: 'masses', type: 'text', help: 'A json with format <code>"partname": mass_in_kg</code>'}
            show:
                fields:
                    - { property: 'model', type: 'file', base_path: '%app.path.models_files%' }
                    - { property: 'image', type: 'image', base_path: '%app.path.models_images%' }
        # List the entity class name you want to manage
        Material:
            class: App\Entity\Material
            list:
                fields:
                    - id
                    - { property: 'price', type: 'float'}
                    - { property: 'available', type: 'toggle'}
                    - { property: 'name', trans: true, domain: 'materials'}
            form:
                fields:
                    - { property: 'price', type: 'number', type_options: { scale: 2 }}
                    - available
                    - { property: 'name', trans: true, domain: 'materials'}
        User:
            class: App\Entity\User
            password_encoding: { algorithm: 'bcrypt', cost: 12 }
            form:
                fields:
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'role', type: 'choice', type_options: {choices:{ User: 'ROLE_USER', Admin: 'ROLE_ADMIN'}}}
            edit:
                fields:
                    - { property: 'passwordResetToken', type: 'text', type_options: { disabled: true }}
            list:
                fields:
                    - id
                    - { property: 'firstName', label: 'First name'}
                    - { property: 'lastName', label: 'Last name'}
                    - email
                    - { property: 'passwordResetToken', type: 'boolean'}
                    - { property: 'role', type: 'string'}
#        - App\Entity\Print
