# config/packages/security.yaml
security:
    # ...
    providers:
        fromMySQL:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User: bcrypt
    firewalls:
        # ...
        main:
            pattern:    ^/
            http_basic: ~
            provider: fromMySQL
            anonymous: ~
            form_login:
                login_path: login
                check_path: login_check
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }