# config/packages/security.yaml
security:
    # ...
    providers:
        fromMySQL:
            entity:
                class: App\Entity\User
                property: email
    encoders:
        App\Entity\User: bcrypt
    firewalls:
        # ...
        main:
            pattern:    ^/
            http_basic: ~
            provider: fromMySQL
            anonymous: ~
            form_login:
                login_path: /login
                check_path: /login_check
            logout:
                path:   /logout
                target: /
    access_control:
        # require ROLE_ADMIN for /admin*
        - { path: ^/admin, roles: ROLE_ADMIN }
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]