vich_uploader:
    db_driver: orm
    mappings:
        models_images:
            uri_prefix:         '%app.path.models_images%'
            upload_destination: '%kernel.root_dir%/../public/%app.path.models_images%'
        models_files:
            uri_prefix: '%app.path.models_files%'
            upload_destination: '%kernel.root_dir%/../public/%app.path.models_files%'