#!/usr/bin/env sh

CONTAINER_NAME=self-3dprint

docker build -t $CONTAINER_NAME .

echo "You may run 'docker tag $CONTAINER_NAME gerkin/$CONTAINER_NAME:latest && docker push gerkin/$CONTAINER_NAME:latest'"