index:
    path: /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/index.html.twig
services:
    path: /services
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/content/services.html.twig
about:
    path: /about
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/content/about.html.twig
contact:
    path: /contact
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/content/contact.html.twig
print-your-own:
    path: /print-your-own
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/content/print-your-own.html.twig
logout:
    path: /logout


easy_admin_bundle:
    resource: "Controller/AdminController.php"
    type:     annotation
    prefix:   /admin


fos_oauth_server_token:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/token.xml"

fos_oauth_server_authorize:
    resource: "@FOSOAuthServerBundle/Resources/config/routing/authorize.xml"