index:
    path: /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/index.html.twig
services:
    path: /services
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/services.html.twig
about:
    path: /about
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/about.html.twig
contact:
    path: /contact
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/contact.html.twig
company-intro:
    path: /company-intro
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: pages/company-intro.html.twig
cart:
  path: /cart
  controller:     Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
        template: pages/cart.html.twig
logout:
    path: /logout
