index:
    path: /
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: index.html.twig
products:
    path: /products
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: products.html.twig
services:
    path: /services
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: services.html.twig
about:
    path: /about
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: about.html.twig
contact:
    path: /contact
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: contact.html.twig
company-intro:
    path: /company-intro
    controller:   Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
        template: company-intro.html.twig
lost-password:
  path: /lost-password
  controller:     Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
        template: lost-password.html.twig
logout:
    path: /logout
